sudo: false
language: node_js
node_js: 6
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - until xwininfo -root > /dev/null 2>&1; do echo "waiting for xvfb"; done
cache:
  directories:
    - node_modules
